<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>13.0</LangVersion>
    <OutputType>Library</OutputType>
    <!-- AssemblyInfo -->
    <AssemblyTitle>UndertaleModLib</AssemblyTitle>
    <ProductName>UndertaleModLib</ProductName>
    <Copyright>Copyright ©  2018-2026, licensed under GPLv3</Copyright>
    <AssemblyVersion>0.9.1.2</AssemblyVersion>
    <FileVersion>0.9.1.2</FileVersion>
    <DebugType>embedded</DebugType>
    <Platforms>AnyCPU;x64</Platforms>
    <RuntimeIdentifiers>win-x64;win-x86</RuntimeIdentifiers>
    <NeutralLanguage>en</NeutralLanguage>
    <ResourceLanguages>en</ResourceLanguages>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
    <!-- Suppress all missing XML comment warnings -->
    <NoWarn>1591</NoWarn>
  </PropertyGroup>
  <PropertyGroup>
    <StartupObject />
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Fody" Version="6.9.3">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Magick.NET-Q8-AnyCPU" Version="14.15.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Scripting" Version="5.6.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.Scripting.Common" Version="5.6.0" />
    <PackageReference Include="PropertyChanged.Fody" Version="4.1.0" PrivateAssets="All" />
    <PackageReference Include="SharpZipLib" Version="1.4.2" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="GameSpecificData\Definitions\deltarune.json" />
    <None Remove="GameSpecificData\Definitions\gamemaker.json" />
    <None Remove="GameSpecificData\Definitions\undertale.json" />
    <None Remove="GameSpecificData\deltarune.json" />
    <None Remove="GameSpecificData\empty.json" />
    <None Remove="GameSpecificData\gamemaker.json" />
    <None Remove="GameSpecificData\README.txt" />
    <None Remove="GameSpecificData\undertale.json" />
    <None Remove="version.txt" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="GameSpecificData\Underanalyzer\deltarune.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="GameSpecificData\Underanalyzer\gamemaker.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="GameSpecificData\Underanalyzer\undertale.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="GameSpecificData\Definitions\deltarune.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="GameSpecificData\Definitions\gamemaker.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="GameSpecificData\Definitions\undertale.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Underanalyzer\Underanalyzer.csproj" />
  </ItemGroup>
  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
       <_Parameter1>UndertaleModLibTests</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>
</Project>
